begin_text = """"Salom! Botga xush kelibsiz!\n\n"
    "Quyida botning qonun-qoidalari:\n"
    "1. Botdan qonuniy maqsadlarda foydalaning.\n"
    "2. Axborot rasmiy manbalarga asoslanadi.\n"
    "3. Noto'g'ri yoki xavfli axborot taqiqlanadi.\n"
    "4. Agar savol yoki shikoyat bo'lsa, pastdagi tugma orqali rahbarga murojaat qiling."
"""
