# Generated by Django 5.1.5 on 2025-01-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(default='0', max_length=255, unique=True),
        ),
    ]
